name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Deploy docs to GitHub Pages
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
      - name: Deploy to Zhamao Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ZHAMAO_XIN_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "/github/workspace/site/"
          REMOTE_HOST: ${{ secrets.ZHAMAO_XIN_HOST }}
          REMOTE_USER: ${{ secrets.ZHAMAO_XIN_USER }}
          TARGET: ${{ secrets.ZHAMAO_XIN_TARGET }}
