name: Static Analysis

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  analyse:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: sunxyw/workflows/setup-environment@main
        with:
          php-version: 8.0
          php-extensions: swoole, posix, json
          operating-system: ubuntu-latest
          use-cache: true

      - name: Static Analysis
        uses: sunxyw/workflows/static-analysis@main
